const palabrasYpistas = [
    { palabra: "ACELERACIÓN", pista: "Tasa de cambio de la velocidad." },
    { palabra: "ÁNGULO", pista: "Medida entre dos líneas que se cruzan." },
    { palabra: "AMPLITUD", pista: "Distancia máxima de una onda desde su eje central." },
    { palabra: "ANÁLISIS", pista: "Estudio detallado de propiedades de funciones." },
    { palabra: "APLICACIONES", pista: "Usos prácticos de conceptos teóricos." },
    { palabra: "APROXIMACION", pista: "Estimación de un valor cercano a la solución exacta de un problema." },
    { palabra: "ASINTOTA", pista: "Recta que se acerca a una curva pero nunca la toca." },
    { palabra: "ASCENDENTE", pista: "Que sube en el eje vertical." },
    { palabra: "CAMBIO", pista: "Variación en una función respecto a una variable." },
    { palabra: "CÍCLICO", pista: "Fenómeno que se repite periódicamente." },
    { palabra: "CIRCUNFERENCIA", pista: "Conjunto de puntos equidistantes de un punto central en un plano." },
    { palabra: "CÓNCAVA", pista: "Forma de una función cuya derivada es decreciente." },
    { palabra: "COORDENADAS", pista: "Valores que definen un punto en el plano." },
    { palabra: "CONCAVIDAD", pista: "Forma de una curva hacia arriba o abajo." },
    { palabra: "CONSTANTE", pista: "Valor fijo en una función." },
    { palabra: "CONTINUIDAD", pista: "Propiedad de una función que no presenta saltos." },
    { palabra: "CONTINUO", pista: "Función sin interrupciones o saltos en su dominio." },
    { palabra: "CONVERGENCIA", pista: "Aproximación de una secuencia a un valor límite." },
    { palabra: "CONVEXA", pista: "Forma de una función cuya derivada es creciente." },
    { palabra: "CONVEXIDAD", pista: "Propiedad de una función donde la línea secante está por encima de la curva." },
    { palabra: "COTA", pista: "Valor que limita un conjunto, superior o inferior." },
    { palabra: "CRITERIOPRIMERADERIVADA", pista: "Regla para determinar extremos usando la primera derivada." },
    { palabra: "CRITERIOSEGUNDADERIVADA", pista: "Regla para determinar si un punto crítico es máximo, mínimo o inflexión usando la segunda derivada." },
    { palabra: "CRÍTICO", pista: "Punto donde la derivada se anula." },
    { palabra: "CRITERIO", pista: "Regla que define cómo analizar propiedades de una función." },
    { palabra: "CRECIMIENTO", pista: "Incremento en el valor de una función." },
    { palabra: "CRECIENTE", pista: "Propiedad de una función cuya pendiente es positiva." },
    { palabra: "CURVA", pista: "Representación gráfica de una función." },
    { palabra: "CURVATURA", pista: "Medida de cómo cambia una curva en un punto." },
    { palabra: "DEMOSTRACION", pista: "Argumento lógico que prueba la veracidad de una proposición." },
    { palabra: "DEFINIDO", pista: "Con un límite claro o establecido." },
    { palabra: "DEFINICIÓN", pista: "Explicación matemática precisa de un concepto." },
    { palabra: "DECRECIENTE", pista: "Propiedad de una función cuya pendiente es negativa." },
    { palabra: "DECRECIMIENTO", pista: "Disminución en el valor de una función." },
    { palabra: "DESCENDENTE", pista: "Que baja en el eje vertical." },
    { palabra: "DERIVADA", pista: "Tasa de cambio instantánea de una función." },
    { palabra: "DERIVADAIMPLICITA", pista: "Método para derivar funciones implícitas." },
    { palabra: "DERIVABLE", pista: "Propiedad de una función que puede ser derivada en un punto." },
    { palabra: "DIFERENCIABLE", pista: "Propiedad que permite derivar una función." },
    { palabra: "DIFERENCIACIÓN", pista: "Proceso de calcular la derivada de una función." },
    { palabra: "DIVERGENCIA", pista: "Operador que mide la magnitud de una fuente o sumidero en un campo vectorial." },
    { palabra: "DOMINIO", pista: "Conjunto de valores donde una función está definida." },
    { palabra: "ECUACIONES", pista: "Igualdades matemáticas que relacionan variables y constantes." },
    { palabra: "ECONOMÍA", pista: "Ciencia que estudia la producción y consumo de bienes." },
    { palabra: "EJE", pista: "Línea de referencia en un sistema de coordenadas." },
    { palabra: "EXPONENCIAL", pista: "Función que crece o decrece rápidamente." },
    { palabra: "EXTREMO", pista: "Punto máximo o mínimo." },
    { palabra: "EXTREMOS", pista: "Máximos y mínimos de una función." },
    { palabra: "EXTREMOLOCAL", pista: "Máximo o mínimo alcanzado por una función en un intervalo específico." },
    { palabra: "FINANZAS", pista: "Rama de la economía relacionada con el dinero." },
    { palabra: "FINITAS", pista: "Que tiene límites definidos." },
    { palabra: "FÍSICA", pista: "Ciencia que estudia el movimiento y las fuerzas." },
    { palabra: "FRACCIÓN", pista: "Representación matemática de una relación entre dos números." },
    { palabra: "FÓRMULA", pista: "Expresión algebraica para calcular propiedades." },
    { palabra: "FUNCION", pista: "Relación entre dos conjuntos que asigna un valor único." },
    { palabra: "FUNCIONCOMPUESTA", pista: "Función formada por la composición de dos funciones." },
    { palabra: "GEOMETRÍA", pista: "Rama de las matemáticas que estudia formas y espacios." },
    { palabra: "GRADIENTE", pista: "Vector que indica la dirección y magnitud del máximo incremento de una función." },
    { palabra: "GRÁFICA", pista: "Representación visual de una función o datos." },
    { palabra: "HESSIANO", pista: "Matriz de segundas derivadas parciales de una función multivariable." },
    { palabra: "HOMOGENEIDAD", pista: "Propiedad de ser igual en todos los puntos o direcciones." },
    { palabra: "HORIZONTAL", pista: "Línea paralela al eje x." },
    { palabra: "IDENTIDADTRIGONOMETRICA", pista: "Ecuación que relaciona funciones trigonométricas y es verdadera para todos los valores de las variables." },
    { palabra: "INDEFINIDO", pista: "Que no tiene un valor específico o límite." },
    { palabra: "INFLEXION", pista: "Punto donde cambia la concavidad de una función." },
    { palabra: "INFIMO", pista: "La mayor cota inferior de un conjunto." },
    { palabra: "INGENIERÍA", pista: "Aplicación de principios matemáticos y físicos." },
    { palabra: "INTERPOLACION", pista: "Método para estimar valores dentro de un conjunto de datos conocidos." },
    { palabra: "INTERVALO", pista: "Rango de valores donde una función está definida." },
    { palabra: "INTEGRAL", pista: "Operación inversa a la derivada." },
    { palabra: "LINEAL", pista: "Relacionado con líneas rectas o funciones de primer grado." },
    { palabra: "LIMITE", pista: "Valor al que tiende una función cuando se acerca a un punto." },
    { palabra: "LIMITEINDETERMINADO", pista: "Situación donde el límite de una función no puede determinarse directamente." },
    { palabra: "LOGARITMO", pista: "Inversa de una función exponencial." },
    { palabra: "LHOPITAL", pista: "Regla para calcular límites indeterminados." },
    { palabra: "MAXIMORELATIVO", pista: "Valor máximo en un intervalo específico de una función." },
    { palabra: "MAXIMIZACIÓN", pista: "Proceso de encontrar el valor más alto posible." },
    { palabra: "MÁXIMO", pista: "Valor más alto que alcanza una función en un intervalo." },
    { palabra: "MEDIO", pista: "Punto entre dos extremos en un intervalo." },
    { palabra: "MINIMORELATIVO", pista: "Valor mínimo en un intervalo específico de una función." },
    { palabra: "MÍNIMO", pista: "Valor más bajo que alcanza una función en un intervalo." },
    { palabra: "MINIMIZACIÓN", pista: "Proceso de encontrar el valor más bajo posible." },
    { palabra: "OSCILACIÓN", pista: "Movimiento periódico en ondas o ciclos." },
    { palabra: "OSCILACIONES", pista: "Movimientos repetitivos alrededor de una posición de equilibrio." },
    { palabra: "OSCILATORIO", pista: "Movimiento o variación repetitiva." },
    { palabra: "ÓPTICA", pista: "Rama de la física relacionada con la luz y las lentes." },
    { palabra: "OPTIMIZACIÓN", pista: "Búsqueda de valores máximos o mínimos en un problema." },
    { palabra: "PARABOLA", pista: "Curva simétrica en forma de 'U' generada por una función cuadrática." },
    { palabra: "PARAMETRO", pista: "Constante que caracteriza una familia de objetos matemáticos." },
    { palabra: "PI", pista: "Constante matemática que representa la relación entre la circunferencia y su diámetro." },
    { palabra: "PENDIENTE", pista: "Razón de cambio entre x y y." },
    { palabra: "POLINOMIO", pista: "Expresión algebraica con términos elevados a potencias." },
    { palabra: "PUNTO", pista: "Ubicación específica en una curva." },
    { palabra: "PUNTOCRITICO", pista: "Punto donde la derivada de una función es cero o no existe." },
    { palabra: "PUNTODEEXTREMO", pista: "Punto donde una función alcanza un valor máximo o mínimo." },
    { palabra: "PUNTODEINFLEXION", pista: "Punto donde una función cambia de concavidad." },
    { palabra: "PUNTOESTACIONARIO", pista: "Punto donde la derivada de una función es cero." },
    { palabra: "PUNTOFIJO", pista: "Valor que permanece inalterado bajo una función dada." },
    { palabra: "RADIAN", pista: "Unidad de medida angular en matemáticas, definida como la relación entre el radio y la longitud de arco." },
    { palabra: "RADIENTE", pista: "Unidad de medida para ángulos." },
    { palabra: "RAÍZ", pista: "Valor que anula una función." },
    { palabra: "RELATIVO", pista: "Comparación entre valores de una función." },
    { palabra: "RESULTADO", pista: "Salida de una operación matemática." },
    { palabra: "ROLLE", pista: "Teorema que garantiza la existencia de un punto crítico entre dos puntos donde la función toma el mismo valor." },
    { palabra: "RANGO", pista: "Conjunto de valores que una función puede tomar." },
    { palabra: "SERIE", pista: "Suma de los términos de una secuencia." },
    { palabra: "SERIESTAYLOR", pista: "Representación de una función como una suma infinita de términos derivados." },
    { palabra: "SECUENCIA", pista: "Serie ordenada de valores." },
    { palabra: "SANDWICH", pista: "Teorema que utiliza funciones para acotar otra y determinar su límite." },
    { palabra: "SECANTE", pista: "Línea que cruza una curva en más de un punto." },
    { palabra: "SEGUNDADERIVADA", pista: "Derivada de la derivada; indica la concavidad de una función." },
    { palabra: "SEGUNDO", pista: "Derivada que describe la concavidad de una curva." },
    { palabra: "SIMETRÍA", pista: "Propiedad de ser igual en ambos lados." },
    { palabra: "SENO", pista: "Función trigonométrica que representa oscilaciones." },
    { palabra: "SUSTITUCIÓN", pista: "Método para resolver límites o integrales." },
    { palabra: "SUPREMO", pista: "La menor cota superior de un conjunto." },
    { palabra: "TEOREMA", pista: "Proposición matemática que se puede demostrar." },
    { palabra: "TEOREMADELVALORMEDIO", pista: "Teorema que asegura la existencia de un punto donde la derivada es igual a la pendiente de la secante." },
    { palabra: "TEOREMADEREGLA", pista: "Teorema que establece reglas específicas para derivar funciones." },
    { palabra: "TRIGONOMETRIA", pista: "Rama de las matemáticas que estudia las relaciones entre los ángulos y lados de los triángulos." },
    { palabra: "TRIGONOMETRICA", pista: "Relacionada con las funciones seno, coseno y tangente." },
    { palabra: "UNICIDAD", pista: "Propiedad de ser único y sin duplicados." },
    { palabra: "VARIABLE", pista: "Símbolo que representa un valor cambiante." },
    { palabra: "VARIABLES", pista: "Elementos que cambian en una función." },
    { palabra: "VALOR", pista: "Resultado que toma una función en un punto." },
    { palabra: "VELOCIDAD", pista: "Tasa de cambio de posición respecto al tiempo." },
    { palabra: "VERTICAL", pista: "Línea paralela al eje y." },
    { palabra: "WEIERSTRASS", pista: "Matemático conocido por su teorema sobre funciones continuas." }
];
